const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Africa/Lagos";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "2347049602299" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "2349042566475";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2347049602299";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "2347049602299,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || "!",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©M-CROSS" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "M-CROSS",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "MCROSS-MD",
  ownername:process.env.OWNER_NAME|| "KING M-CROSS",

  sessionName:process.env.SESSION_ID || "SUHAIL_12_56_10_22_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjQwLFxuICAgICAgICAyMDQsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMTA5LFxuICAgICAgICAyMTksXG4gICAgICAgIDE5OSxcbiAgICAgICAgNjUsXG4gICAgICAgIDMxLFxuICAgICAgICAyNCxcbiAgICAgICAgMjQyLFxuICAgICAgICA3OSxcbiAgICAgICAgMTk4LFxuICAgICAgICA4MyxcbiAgICAgICAgMjQ5LFxuICAgICAgICA1NixcbiAgICAgICAgOTIsXG4gICAgICAgIDUxLFxuICAgICAgICA0NSxcbiAgICAgICAgMjE1LFxuICAgICAgICAzNSxcbiAgICAgICAgMTU1LFxuICAgICAgICAyMzMsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMjQ4LFxuICAgICAgICAyNTUsXG4gICAgICAgIDE2OSxcbiAgICAgICAgNzUsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTg3LFxuICAgICAgICAyMjksXG4gICAgICAgIDIwOSxcbiAgICAgICAgNzdcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTgzLFxuICAgICAgICAxMTEsXG4gICAgICAgIDEwLFxuICAgICAgICAxNDksXG4gICAgICAgIDE5NCxcbiAgICAgICAgMTYxLFxuICAgICAgICA2MSxcbiAgICAgICAgMTMzLFxuICAgICAgICA0MixcbiAgICAgICAgMTM4LFxuICAgICAgICAyNDgsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMTUsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMjMzLFxuICAgICAgICAyNTIsXG4gICAgICAgIDQ0LFxuICAgICAgICAxMTEsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTE2LFxuICAgICAgICAxNjksXG4gICAgICAgIDEzLFxuICAgICAgICA5OSxcbiAgICAgICAgODksXG4gICAgICAgIDc3LFxuICAgICAgICAxNzksXG4gICAgICAgIDIyNixcbiAgICAgICAgNjksXG4gICAgICAgIDg3LFxuICAgICAgICAxMzksXG4gICAgICAgIDE3NCxcbiAgICAgICAgNDRcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQwLFxuICAgICAgICA0LFxuICAgICAgICAxNjAsXG4gICAgICAgIDMzLFxuICAgICAgICAyNDksXG4gICAgICAgIDQsXG4gICAgICAgIDg3LFxuICAgICAgICAzNyxcbiAgICAgICAgMjA0LFxuICAgICAgICAxNDYsXG4gICAgICAgIDI1MixcbiAgICAgICAgMTA0LFxuICAgICAgICA0MSxcbiAgICAgICAgNzAsXG4gICAgICAgIDk4LFxuICAgICAgICAxNTAsXG4gICAgICAgIDM1LFxuICAgICAgICAzNyxcbiAgICAgICAgMTYyLFxuICAgICAgICAxMTIsXG4gICAgICAgIDE5OCxcbiAgICAgICAgNTQsXG4gICAgICAgIDEwNSxcbiAgICAgICAgODMsXG4gICAgICAgIDExMyxcbiAgICAgICAgMTQ5LFxuICAgICAgICAyMDcsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMCxcbiAgICAgICAgMTI0LFxuICAgICAgICAxOTEsXG4gICAgICAgIDc3XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIyNCxcbiAgICAgICAgMjAzLFxuICAgICAgICA4NyxcbiAgICAgICAgMTUzLFxuICAgICAgICAxNDEsXG4gICAgICAgIDE4MyxcbiAgICAgICAgOCxcbiAgICAgICAgMjMsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTA1LFxuICAgICAgICAxNTgsXG4gICAgICAgIDIzMixcbiAgICAgICAgOTMsXG4gICAgICAgIDE0MyxcbiAgICAgICAgNzYsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMjQ0LFxuICAgICAgICAyMTAsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTY0LFxuICAgICAgICAxMDMsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTIsXG4gICAgICAgIDM4LFxuICAgICAgICAxODEsXG4gICAgICAgIDMyLFxuICAgICAgICAxMTUsXG4gICAgICAgIDEwMyxcbiAgICAgICAgNDIsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMjIyLFxuICAgICAgICAxNVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjI0LFxuICAgICAgICAxMzIsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTc4LFxuICAgICAgICA3MCxcbiAgICAgICAgMTYsXG4gICAgICAgIDEwMyxcbiAgICAgICAgODcsXG4gICAgICAgIDczLFxuICAgICAgICA1MCxcbiAgICAgICAgMjAsXG4gICAgICAgIDI4LFxuICAgICAgICA3MixcbiAgICAgICAgMTA5LFxuICAgICAgICA2NyxcbiAgICAgICAgMzYsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMjMxLFxuICAgICAgICAxNDMsXG4gICAgICAgIDEwMixcbiAgICAgICAgMTk2LFxuICAgICAgICAxNTIsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTU2LFxuICAgICAgICA5NixcbiAgICAgICAgNTIsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTgwLFxuICAgICAgICA0NyxcbiAgICAgICAgMjE4LFxuICAgICAgICA2MSxcbiAgICAgICAgNjRcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTc5LFxuICAgICAgICAyMTUsXG4gICAgICAgIDEyNCxcbiAgICAgICAgODcsXG4gICAgICAgIDExNyxcbiAgICAgICAgMjMzLFxuICAgICAgICA1NCxcbiAgICAgICAgMjMxLFxuICAgICAgICAzOSxcbiAgICAgICAgMTE0LFxuICAgICAgICAxMTcsXG4gICAgICAgIDg5LFxuICAgICAgICAxNTYsXG4gICAgICAgIDE5MyxcbiAgICAgICAgODAsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMjE4LFxuICAgICAgICAxOTgsXG4gICAgICAgIDQzLFxuICAgICAgICAyMzYsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMTUsXG4gICAgICAgIDIyLFxuICAgICAgICA4OCxcbiAgICAgICAgMjA2LFxuICAgICAgICA2MixcbiAgICAgICAgMTU1LFxuICAgICAgICAxOTksXG4gICAgICAgIDE5NCxcbiAgICAgICAgMjE0LFxuICAgICAgICAyNDAsXG4gICAgICAgIDI2XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDEzNixcbiAgICAgICAgICAxMixcbiAgICAgICAgICA2NCxcbiAgICAgICAgICAxNjEsXG4gICAgICAgICAgMTQ1LFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDAsXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDIwMixcbiAgICAgICAgICAxOTIsXG4gICAgICAgICAgMTk2LFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDE4NSxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgMTExLFxuICAgICAgICAgIDIzNCxcbiAgICAgICAgICAxMjksXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDUwLFxuICAgICAgICAgIDE0NyxcbiAgICAgICAgICAxNTgsXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDcwLFxuICAgICAgICAgIDIxNyxcbiAgICAgICAgICA0MCxcbiAgICAgICAgICAxNDEsXG4gICAgICAgICAgNjQsXG4gICAgICAgICAgOTJcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDIyLFxuICAgICAgICAgIDI0OCxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgNzIsXG4gICAgICAgICAgMTkwLFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAyMTksXG4gICAgICAgICAgMTU3LFxuICAgICAgICAgIDE4NyxcbiAgICAgICAgICA5OCxcbiAgICAgICAgICAxOTEsXG4gICAgICAgICAgMjEwLFxuICAgICAgICAgIDE5LFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAxODgsXG4gICAgICAgICAgMjU0LFxuICAgICAgICAgIDE3OCxcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgOTIsXG4gICAgICAgICAgODksXG4gICAgICAgICAgMjQwLFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICA0NCxcbiAgICAgICAgICA1OSxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgNzMsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDQ0LFxuICAgICAgICAgIDYyXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTAzLFxuICAgICAgICAyMzAsXG4gICAgICAgIDE3MyxcbiAgICAgICAgNTgsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTQ3LFxuICAgICAgICA2LFxuICAgICAgICAyNDIsXG4gICAgICAgIDgxLFxuICAgICAgICAxNDMsXG4gICAgICAgIDQsXG4gICAgICAgIDIzMixcbiAgICAgICAgNzcsXG4gICAgICAgIDkzLFxuICAgICAgICAyNDQsXG4gICAgICAgIDE5MixcbiAgICAgICAgNDQsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMzYsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTIyLFxuICAgICAgICAyOCxcbiAgICAgICAgMjcsXG4gICAgICAgIDQzLFxuICAgICAgICAyMjksXG4gICAgICAgIDExMCxcbiAgICAgICAgMTA2LFxuICAgICAgICAxMjksXG4gICAgICAgIDMsXG4gICAgICAgIDExOSxcbiAgICAgICAgNTAsXG4gICAgICAgIDE2NixcbiAgICAgICAgNzksXG4gICAgICAgIDExOSxcbiAgICAgICAgMTY1LFxuICAgICAgICAyNSxcbiAgICAgICAgMTM5LFxuICAgICAgICAxMixcbiAgICAgICAgMjAyLFxuICAgICAgICAxNjYsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMjMwLFxuICAgICAgICAyMTYsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTMyLFxuICAgICAgICAxODcsXG4gICAgICAgIDE1MyxcbiAgICAgICAgNjksXG4gICAgICAgIDcxLFxuICAgICAgICA2MCxcbiAgICAgICAgMTI4LFxuICAgICAgICAxNzEsXG4gICAgICAgIDEwMixcbiAgICAgICAgMTQ4LFxuICAgICAgICA1OSxcbiAgICAgICAgMTMsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMTUwLFxuICAgICAgICAxODIsXG4gICAgICAgIDQ4LFxuICAgICAgICA0MSxcbiAgICAgICAgMjMyLFxuICAgICAgICA0OCxcbiAgICAgICAgMTFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDIzMCxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJNSGovVTBQekttYVpJZmVNWlpRM0VyT0grOVZKNzVGYWtsZkpMdkNEZklvPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDcwNDk2MDIyOTlAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkIwQjM3NDYzOEI3NkU4NjQ1OUNBRjI1OTA2MDVGQjhEXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyOTYwMTgxMFxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDcwNDk2MDIyOTlAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkI4NkJDNjBCOUU2NTI4M0U3MTlBMDYzOEI3MzBEREY3XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyOTYwMTgxMVxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJ0X1ZnVi1Bd1FUU1JFTVRsaW8wR3ZRXCIsXG4gIFwicGhvbmVJZFwiOiBcIjQ2MWY5NThmLTE3OTgtNDEwYi05ZDA2LWE2ODc1NWQ4ZmJlMFwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyNTMsXG4gICAgICAxNzgsXG4gICAgICA5NSxcbiAgICAgIDEzNyxcbiAgICAgIDkyLFxuICAgICAgMTYyLFxuICAgICAgMjIzLFxuICAgICAgNzgsXG4gICAgICAxNCxcbiAgICAgIDIyMSxcbiAgICAgIDE3MyxcbiAgICAgIDExMCxcbiAgICAgIDE5MyxcbiAgICAgIDM1LFxuICAgICAgNDgsXG4gICAgICA4OCxcbiAgICAgIDE5NyxcbiAgICAgIDEzMCxcbiAgICAgIDEwNixcbiAgICAgIDIzOVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxMjksXG4gICAgICAyMzAsXG4gICAgICAxMDksXG4gICAgICAzMyxcbiAgICAgIDE5LFxuICAgICAgMTg1LFxuICAgICAgMjQ0LFxuICAgICAgMTI4LFxuICAgICAgOTYsXG4gICAgICA3MSxcbiAgICAgIDc2LFxuICAgICAgMTUwLFxuICAgICAgMjI4LFxuICAgICAgMTY5LFxuICAgICAgMjU1LFxuICAgICAgMTEzLFxuICAgICAgMjEzLFxuICAgICAgMTI4LFxuICAgICAgMjA2LFxuICAgICAgNDlcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiUThOQlpMMkNcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjIzNDcwNDk2MDIyOTk6MTNAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjcwMzU2NTk3NjM5MzI6MTNAbGlkXCIsXG4gICAgXCJuYW1lXCI6IFwi44Wk44Wk44Wk44WkXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDSkRCdnRjQ0VJckMzcmdHR0FFZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCI3MGpUZ0RPZmx3b0hWQmo0VGlMTXM1enRTdktmV29icmNMUGNEcEN3c1RrPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcInQyNEpzb3JBU1BHVWpuOTV4NTMrcjAvNjQ2QjR5SGRrOW9ybmRjYzd6YVUreXdIT2RNUXQ5cXZDdWc3YXU5T3plc3VJNGhHQnZOZktablhZb1F3QkNRPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIkdpcTNrNDJMejBvL0RtMEJxdVRFVCtSNDN3dFNvMVo2UWRQQ0NxMWFHbU5HeEtzQ2JRejNERVBxajErc2xFQWc3T0xnMkNVQXBvdjNvSzhWa3FHK0N3PT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjIzNDcwNDk2MDIyOTk6MTNAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgNzIsXG4gICAgICAgICAgMjExLFxuICAgICAgICAgIDEyOCxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAxNTksXG4gICAgICAgICAgMTUxLFxuICAgICAgICAgIDEwLFxuICAgICAgICAgIDcsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgMjQ4LFxuICAgICAgICAgIDc4LFxuICAgICAgICAgIDM0LFxuICAgICAgICAgIDIwNCxcbiAgICAgICAgICAxNzksXG4gICAgICAgICAgMTU2LFxuICAgICAgICAgIDIzNyxcbiAgICAgICAgICA3NCxcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDkwLFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICAyMzUsXG4gICAgICAgICAgMTEyLFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAyMjAsXG4gICAgICAgICAgMTQsXG4gICAgICAgICAgMTQ0LFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICAxNzcsXG4gICAgICAgICAgNTdcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcImFuZHJvaWRcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyOTYwMTgwNyxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQUhuWVwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSG5ZLmpzb24iOiAie1wia2V5RGF0YVwiOlwiWTMvdU1oVG1nN0gxZFBOcFlmRnkzcHArclMvZmExOG94QktGL05lUk5Ydz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjo3MjAzNDcyODAsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyOTYwMTgxMjA2MFwifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "NEZUKO",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
